{"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/internalError"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niohttp2\/http2errorcode\/internalerror"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"NIOHTTP2"}],"title":"internalError","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","kind":"typeIdentifier"}],"externalID":"s:8NIOHTTP214HTTP2ErrorCodeV08internalC0ACvpZ"},"abstract":[{"type":"text","text":"The endpoint encountered an unexpected internal error."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","kind":"typeIdentifier"}],"platforms":["Linux"],"languages":["swift"]}]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","title":"NIOHTTP2","kind":"symbol","role":"collection","url":"\/documentation\/niohttp2","type":"topic","abstract":[]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode/internalError":{"type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/internalError","url":"\/documentation\/niohttp2\/http2errorcode\/internalerror","abstract":[{"text":"The endpoint encountered an unexpected internal error.","type":"text"}],"kind":"symbol","title":"internalError","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","kind":"typeIdentifier"}],"role":"symbol"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTP2ErrorCode"}],"type":"topic","abstract":[{"type":"text","text":"An HTTP\/2 error code."}],"role":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","title":"HTTP2ErrorCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTP2ErrorCode"}],"url":"\/documentation\/niohttp2\/http2errorcode"}}}